package Form.Internal;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import koneksi.Koneksi;

/**
 *
 * @author Administrator
 */
public class crud_anggota extends javax.swing.JInternalFrame {
    Date date = new Date();
    Connection sqlConnection = null;
    Statement sqlStatement = null;
    ResultSet sqlResultSet = null;
    koneksi.Koneksi conn = new Koneksi();
    private static final DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form crud_anggota
     */
    public crud_anggota() {
        initComponents();
        makeCenter();
    }
    
    private void makeCenter() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_anggota = new javax.swing.JTabbedPane();
        pnl_anggota = new javax.swing.JPanel();
        aerithLabel1 = new aerith.swing.AerithLabel();
        aerithLabel2 = new aerith.swing.AerithLabel();
        aerithLabel14 = new aerith.swing.AerithLabel();
        aerithLabel15 = new aerith.swing.AerithLabel();
        aerithLabel16 = new aerith.swing.AerithLabel();
        no_ktp = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tmpt_lahir = new javax.swing.JTextField();
        tgl_lahir = new com.toedter.calendar.JDateChooser();
        aerithLabel17 = new aerith.swing.AerithLabel();
        aerithLabel18 = new aerith.swing.AerithLabel();
        aerithLabel19 = new aerith.swing.AerithLabel();
        lokasi = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        nik_bmt = new javax.swing.JTextField();
        btn_clear = new aerith.swing.AerithActionButton();
        btn_daftar = new aerith.swing.AerithActionButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        pnl_anggota1 = new javax.swing.JPanel();
        aerithLabel3 = new aerith.swing.AerithLabel();
        aerithLabel4 = new aerith.swing.AerithLabel();
        aerithLabel20 = new aerith.swing.AerithLabel();
        aerithLabel21 = new aerith.swing.AerithLabel();
        aerithLabel22 = new aerith.swing.AerithLabel();
        txtno_ktpubah = new javax.swing.JTextField();
        txtnama_ubah = new javax.swing.JTextField();
        txt_templahirubah = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        aerithLabel23 = new aerith.swing.AerithLabel();
        aerithLabel24 = new aerith.swing.AerithLabel();
        aerithLabel25 = new aerith.swing.AerithLabel();
        txt_lksusahaubah = new javax.swing.JTextField();
        txt_jnsusaha_ubah = new javax.swing.JTextField();
        txt_nikbmtubah = new javax.swing.JTextField();
        aerithActionButton3 = new aerith.swing.AerithActionButton();
        btn_ubah = new aerith.swing.AerithActionButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalamat_ubah = new javax.swing.JTextArea();

        setClosable(true);

        tab_anggota.setBackground(new java.awt.Color(102, 102, 255));
        tab_anggota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        pnl_anggota.setBackground(new java.awt.Color(102, 102, 255));

        aerithLabel1.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel1.setText("NO.KTP :");
        aerithLabel1.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel2.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel2.setText("NAMA :");
        aerithLabel2.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel14.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel14.setText("ALAMAT :");
        aerithLabel14.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel15.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel15.setText("TEMPAT LAHIR :");
        aerithLabel15.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel16.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel16.setText("TANGGAL LAHIR :");
        aerithLabel16.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        no_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_ktpActionPerformed(evt);
            }
        });
        no_ktp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                no_ktpKeyPressed(evt);
            }
        });

        tgl_lahir.setDateFormatString("YYYY-MM-dd");
        tgl_lahir.setMaxSelectableDate(null);
        tgl_lahir.setMinSelectableDate(new java.util.Date(-631173512000L));

        aerithLabel17.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel17.setText("LOKASI USAHA :");
        aerithLabel17.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel18.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel18.setText("JENIS USAHA :");
        aerithLabel18.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel19.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel19.setText("NIK BMT :");
        aerithLabel19.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        btn_clear.setText("CANCEL");
        btn_clear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_daftar.setText("DAFTAR");
        btn_daftar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        javax.swing.GroupLayout pnl_anggotaLayout = new javax.swing.GroupLayout(pnl_anggota);
        pnl_anggota.setLayout(pnl_anggotaLayout);
        pnl_anggotaLayout.setHorizontalGroup(
            pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aerithLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aerithLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aerithLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_anggotaLayout.createSequentialGroup()
                        .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aerithLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aerithLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aerithLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lokasi)
                            .addComponent(jenis)
                            .addComponent(nik_bmt, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(pnl_anggotaLayout.createSequentialGroup()
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnl_anggotaLayout.setVerticalGroup(
            pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aerithLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_anggotaLayout.createSequentialGroup()
                        .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aerithLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nik_bmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tab_anggota.addTab("Daftar Anggota BMT", pnl_anggota);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        pnl_anggota1.setBackground(new java.awt.Color(102, 102, 255));

        aerithLabel3.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel3.setText("NO.KTP :");
        aerithLabel3.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel4.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel4.setText("NAMA :");
        aerithLabel4.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel20.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel20.setText("ALAMAT :");
        aerithLabel20.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel21.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel21.setText("TEMPAT LAHIR :");
        aerithLabel21.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel22.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel22.setText("TANGGAL LAHIR :");
        aerithLabel22.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        txtno_ktpubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_ktpubahActionPerformed(evt);
            }
        });
        txtno_ktpubah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtno_ktpubahKeyPressed(evt);
            }
        });

        jDateChooser2.setDateFormatString("YYYY-MM-dd");
        jDateChooser2.setMaxSelectableDate(null);
        jDateChooser2.setMinSelectableDate(new java.util.Date(-631173512000L));

        aerithLabel23.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel23.setText("LOKASI USAHA :");
        aerithLabel23.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel24.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel24.setText("JENIS USAHA :");
        aerithLabel24.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithLabel25.setForeground(new java.awt.Color(0, 0, 0));
        aerithLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aerithLabel25.setText("NIK BMT :");
        aerithLabel25.setFont(new java.awt.Font("Default", 1, 12)); // NOI18N

        aerithActionButton3.setText("CANCEL");
        aerithActionButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        aerithActionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aerithActionButton3ActionPerformed(evt);
            }
        });

        btn_ubah.setText("SIMPAN");
        btn_ubah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        txtalamat_ubah.setColumns(20);
        txtalamat_ubah.setRows(5);
        jScrollPane2.setViewportView(txtalamat_ubah);

        javax.swing.GroupLayout pnl_anggota1Layout = new javax.swing.GroupLayout(pnl_anggota1);
        pnl_anggota1.setLayout(pnl_anggota1Layout);
        pnl_anggota1Layout.setHorizontalGroup(
            pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_anggota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aerithLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aerithLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aerithLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnama_ubah)
                    .addComponent(txt_templahirubah)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(txtno_ktpubah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_anggota1Layout.createSequentialGroup()
                        .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aerithLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aerithLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aerithLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_lksusahaubah)
                            .addComponent(txt_jnsusaha_ubah)
                            .addComponent(txt_nikbmtubah, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(pnl_anggota1Layout.createSequentialGroup()
                        .addComponent(aerithActionButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnl_anggota1Layout.setVerticalGroup(
            pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_anggota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtno_ktpubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lksusahaubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnama_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aerithLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jnsusaha_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aerithLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_anggota1Layout.createSequentialGroup()
                        .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aerithLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nikbmtubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aerithActionButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aerithLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_templahirubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_anggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aerithLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_anggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_anggota1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tab_anggota.addTab("Ubah Anggota BMT", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_anggota)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_anggota)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_ktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_ktpActionPerformed

    private void txtno_ktpubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_ktpubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_ktpubahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try {
            sqlConnection = conn.bukaKoneksi();
            sqlStatement = sqlConnection.createStatement();
            
            StringBuffer buff = new StringBuffer();
            buff.append("UPDATE data_anggota_bmt SET NAMA='").append(txtnama_ubah.getText()).append("',ALAMAT='")
                .append(txtalamat_ubah.getText()).append(",TEMPAT_LAHIR='").append(txt_templahirubah.getText()).append(",TANGGAL_LAHIR='")
                .append(sdf.format(jDateChooser2.getDate())).append(",LOKASI_USAHA='").append(txt_lksusahaubah.getText()).append(",JENIS_USAHA='")
                .append(txt_jnsusaha_ubah.getText()).append(",NIK_BMT='").append(txt_nikbmtubah.getText())
                .append("' WHERE NO_KTP='").append(no_ktp.getText()).append("' ");
            
            sqlResultSet = sqlStatement.executeQuery(buff.toString());
            JOptionPane.showMessageDialog(null, "Update Data Success..", "Information", JOptionPane.INFORMATION_MESSAGE);
            clear1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        try {
            if(no_ktp.getText() != null || nik_bmt.getText() != null)
            {
                sqlConnection = conn.bukaKoneksi();
                sqlStatement = sqlConnection.createStatement();
                
                StringBuffer buff = new StringBuffer();
                buff.append("INSERT INTO data_anggota_bmt VALUES('").append(no_ktp.getText()).append("','")
                    .append(nama.getText()).append("','").append(alamat.getText()).append("','")
                    .append(tmpt_lahir.getText()).append("','").append(sdf.format(tgl_lahir.getDate())).append("','")
                    .append(lokasi.getText()).append("','").append(jenis.getText()).append("','")
                    .append(nik_bmt.getText());
                
                sqlResultSet = sqlStatement.executeQuery(buff.toString());
                
                if(sqlResultSet.next())
                {
                    JOptionPane.showMessageDialog(null, "Save data success..!!", "Information", JOptionPane.ERROR);
                    clear();
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void no_ktpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_ktpKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_no_ktpKeyPressed

    private void txtno_ktpubahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtno_ktpubahKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            try {
                sqlConnection = conn.bukaKoneksi();
                sqlStatement = sqlConnection.createStatement();
                
                String ktp = no_ktp.getText().trim();
                StringBuffer buff = new StringBuffer();
                buff.append("SELECT * FROM data_anggota_bmt WHERE NO_KTP ='").append(ktp).append("'");
                sqlResultSet = sqlStatement.executeQuery(buff.toString());
                
                if(sqlResultSet.next())
                {
                    txtno_ktpubah.setEnabled(false);
                    txtnama_ubah.setText(sqlResultSet.getString(2));
                    txtalamat_ubah.setText(sqlResultSet.getString(3));
                    txt_templahirubah.setText(sqlResultSet.getString(4));
                    jDateChooser2.setDate(sqlResultSet.getDate(5));
                    txt_lksusahaubah.setText(sqlResultSet.getString(6));
                    txt_jnsusaha_ubah.setText(sqlResultSet.getString(7));
                    txt_nikbmtubah.setText(sqlResultSet.getString(8));
                }else{
                    txtnama_ubah.isFocusable();
                }
                
            } catch (Exception e) {
                e.printStackTrace();
            }
                    
        }
    }//GEN-LAST:event_txtno_ktpubahKeyPressed

    private void aerithActionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aerithActionButton3ActionPerformed
        // TODO add your handling code here:
        clear1();
    }//GEN-LAST:event_aerithActionButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aerith.swing.AerithActionButton aerithActionButton3;
    private aerith.swing.AerithLabel aerithLabel1;
    private aerith.swing.AerithLabel aerithLabel14;
    private aerith.swing.AerithLabel aerithLabel15;
    private aerith.swing.AerithLabel aerithLabel16;
    private aerith.swing.AerithLabel aerithLabel17;
    private aerith.swing.AerithLabel aerithLabel18;
    private aerith.swing.AerithLabel aerithLabel19;
    private aerith.swing.AerithLabel aerithLabel2;
    private aerith.swing.AerithLabel aerithLabel20;
    private aerith.swing.AerithLabel aerithLabel21;
    private aerith.swing.AerithLabel aerithLabel22;
    private aerith.swing.AerithLabel aerithLabel23;
    private aerith.swing.AerithLabel aerithLabel24;
    private aerith.swing.AerithLabel aerithLabel25;
    private aerith.swing.AerithLabel aerithLabel3;
    private aerith.swing.AerithLabel aerithLabel4;
    private javax.swing.JTextArea alamat;
    private aerith.swing.AerithActionButton btn_clear;
    private aerith.swing.AerithActionButton btn_daftar;
    private aerith.swing.AerithActionButton btn_ubah;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField lokasi;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik_bmt;
    private javax.swing.JTextField no_ktp;
    private javax.swing.JPanel pnl_anggota;
    private javax.swing.JPanel pnl_anggota1;
    private javax.swing.JTabbedPane tab_anggota;
    private com.toedter.calendar.JDateChooser tgl_lahir;
    private javax.swing.JTextField tmpt_lahir;
    private javax.swing.JTextField txt_jnsusaha_ubah;
    private javax.swing.JTextField txt_lksusahaubah;
    private javax.swing.JTextField txt_nikbmtubah;
    private javax.swing.JTextField txt_templahirubah;
    private javax.swing.JTextArea txtalamat_ubah;
    private javax.swing.JTextField txtnama_ubah;
    private javax.swing.JTextField txtno_ktpubah;
    // End of variables declaration//GEN-END:variables

    public void clear()
    {
        no_ktp.setText("");
        nama.setText("");
        alamat.setText("");
        tmpt_lahir.setText("");
        tgl_lahir.setDate(date);
        lokasi.setText("");
        jenis.setText("");
        nik_bmt.setText("");
    }
    
     public void clear1()
    {
        txtno_ktpubah.setText("");
        txtnama_ubah.setText("");
        txtalamat_ubah.setText("");
        txt_templahirubah.setText("");
        jDateChooser2.setDate(date);
        txt_lksusahaubah.setText("");
        txt_jnsusaha_ubah.setText("");
        txt_nikbmtubah.setText("");
    }
}
